export const itemClassification: string[] = ['Brand', 'Category', 'Subcategory', 'Type'];
export const itemClasses = [
  { id: 1, name: 'Root', parentId: 0 },
  { id: 2, name: 'Jaquar', parentId: 1 },
  { id: 3, name: 'Sanitaryware', parentId: 2 },
  { id: 17, name: 'Essco', parentId: 1 },
  { id: 18, name: 'Sanitaryware', parentId: 17 },
  { id: 20, name: 'Marvel', parentId: 137 },
  { id: 23, name: 'Viking', parentId: 1 },
  { id: 24, name: 'Cisterns', parentId: 2 },
  { id: 25, name: 'Alive', parentId: 106 },
  { id: 27, name: 'Hot Water Solutions', parentId: 2 },
  { id: 28, name: 'Cisterns', parentId: 17 },
  { id: 29, name: 'Faucets', parentId: 2 },
  { id: 30, name: 'Kubix Prime', parentId: 29 },
  { id: 31, name: 'Opal Prime', parentId: 29 },
  { id: 32, name: 'Ornamix Prime', parentId: 29 },
  { id: 33, name: 'Alive', parentId: 29 },
  { id: 34, name: 'Lyric', parentId: 29 },
  { id: 35, name: 'Aria', parentId: 29 },
  { id: 36, name: 'Fonte', parentId: 29 },
  { id: 37, name: "D'Arc", parentId: 29 },
  { id: 38, name: 'Vignette Prime', parentId: 29 },
  { id: 39, name: 'Fusion', parentId: 29 },
  { id: 40, name: 'Solo', parentId: 29 },
  { id: 41, name: "Queen's", parentId: 29 },
  { id: 42, name: 'Florentine', parentId: 29 },
  { id: 43, name: 'Clarion', parentId: 29 },
  { id: 44, name: 'Continental', parentId: 29 },
  { id: 45, name: 'Sensor Taps', parentId: 29 },
  { id: 46, name: 'Pressmatic', parentId: 29 },
  { id: 47, name: 'Flush Valves', parentId: 29 },
  { id: 48, name: 'Bathtub Spouts', parentId: 29 },
  { id: 49, name: 'Bath Accessories', parentId: 29 },
  { id: 50, name: 'Allied', parentId: 29 },
  { id: 51, name: 'Showers', parentId: 29 },
  { id: 52, name: 'Thermostatic Mixers', parentId: 29 },
  { id: 53, name: 'Urinals', parentId: 106 },
  { id: 54, name: 'Astra', parentId: 29 },
  { id: 55, name: 'Dummy', parentId: 29 },
  { id: 56, name: 'Eko', parentId: 29 },
  { id: 57, name: 'Hand Dryer', parentId: 29 },
  { id: 58, name: 'Kleen', parentId: 29 },
  { id: 59, name: 'Kubix-F', parentId: 29 },
  { id: 60, name: 'Opal', parentId: 29 },
  { id: 61, name: 'Ornamix', parentId: 29 },
  { id: 62, name: 'Vignette', parentId: 29 },
  { id: 63, name: 'Nirali', parentId: 1 },
  { id: 65, name: '.', parentId: 1 },
  { id: 67, name: 'Urinals', parentId: 137 },
  { id: 68, name: 'Faucets', parentId: 17 },
  { id: 69, name: 'Something Special', parentId: 68 },
  { id: 70, name: 'Allied', parentId: 68 },
  { id: 71, name: 'Cosmos', parentId: 68 },
  { id: 72, name: 'Delux', parentId: 68 },
  { id: 73, name: 'Marvel', parentId: 68 },
  { id: 74, name: 'Tropical', parentId: 68 },
  { id: 75, name: 'Accessories', parentId: 68 },
  { id: 76, name: 'Aspire', parentId: 68 },
  { id: 77, name: 'Wellness', parentId: 2 },
  { id: 78, name: 'Shower Panel', parentId: 77 },
  { id: 79, name: 'Bathtub Accessories', parentId: 77 },
  { id: 80, name: 'Built in Bath Tub', parentId: 77 },
  { id: 83, name: 'Spares', parentId: 77 },
  { id: 84, name: 'Spas', parentId: 77 },
  { id: 85, name: 'Steam Solutions', parentId: 77 },
  { id: 86, name: 'Whirlpool', parentId: 77 },
  { id: 87, name: 'Shower Enclosure', parentId: 2 },
  { id: 88, name: 'Artize', parentId: 1 },
  { id: 89, name: 'Faucets', parentId: 88 },
  { id: 91, name: 'Hot Water Solutions', parentId: 17 },
  { id: 92, name: 'Jaquar Spares', parentId: 1 },
  { id: 93, name: 'Commander', parentId: 1 },
  { id: 95, name: 'Sanitaryware', parentId: 88 },
  { id: 96, name: 'ACPL', parentId: 1 },
  { id: 97, name: 'Ornamix Prime', parentId: 106 },
  { id: 99, name: 'Sanjay Chilly', parentId: 1 },
  { id: 100, name: 'Flush Plates', parentId: 24 },
  { id: 101, name: 'Exposed', parentId: 24 },
  { id: 102, name: 'Concealed', parentId: 24 },
  { id: 103, name: 'Insta Prime', parentId: 27 },
  { id: 104, name: 'Instant', parentId: 27 },
  { id: 105, name: 'Storage', parentId: 27 },
  { id: 106, name: 'WC & Basins', parentId: 3 },
  { id: 107, name: 'Florentine', parentId: 106 },
  { id: 108, name: 'Ped,SC,Cis,Acc', parentId: 3 },
  { id: 109, name: 'Florentine', parentId: 108 },
  { id: 110, name: 'Vignette', parentId: 106 },
  { id: 111, name: 'Vignette', parentId: 108 },
  { id: 112, name: 'Continental', parentId: 106 },
  { id: 113, name: 'Continental', parentId: 108 },
  { id: 114, name: "D'Arc", parentId: 106 },
  { id: 115, name: 'Opal', parentId: 106 },
  { id: 116, name: 'Opal', parentId: 108 },
  { id: 117, name: 'Solo', parentId: 106 },
  { id: 118, name: 'Solo', parentId: 108 },
  { id: 119, name: 'Fonte', parentId: 106 },
  { id: 120, name: 'Fonte', parentId: 108 },
  { id: 121, name: 'Aria', parentId: 108 },
  { id: 122, name: 'Aria', parentId: 106 },
  { id: 123, name: 'Lyric', parentId: 106 },
  { id: 124, name: 'Lyric', parentId: 108 },
  { id: 125, name: 'Fusion', parentId: 106 },
  { id: 126, name: 'Kubix', parentId: 106 },
  { id: 127, name: 'Kubix', parentId: 108 },
  { id: 128, name: "Queen's", parentId: 106 },
  { id: 129, name: "Queen's", parentId: 108 },
  { id: 130, name: 'Arc', parentId: 106 },
  { id: 131, name: 'Arc', parentId: 108 },
  { id: 132, name: 'JDS-Jaquar Designer Range', parentId: 106 },
  { id: 133, name: 'Ornamix Prime', parentId: 108 },
  { id: 134, name: 'Wellness', parentId: 88 },
  { id: 135, name: 'Bidspa', parentId: 106 },
  { id: 137, name: 'WC & Basins', parentId: 18 },
  { id: 139, name: 'Aspire', parentId: 137 },
  { id: 140, name: 'Ped,SC,Cis,Acc', parentId: 18 },
  { id: 141, name: 'Aspire', parentId: 140 },
  { id: 142, name: 'Cosmo', parentId: 137 },
  { id: 143, name: 'Cosmo', parentId: 140 },
  { id: 144, name: 'ECS', parentId: 137 },
  { id: 145, name: 'ECS', parentId: 140 },
  { id: 146, name: 'Sauna', parentId: 77 },
  { id: 147, name: 'Bonomini', parentId: 1 },
  { id: 148, name: 'Bottle Trap', parentId: 147 },
  { id: 149, name: 'Chrome', parentId: 148 },
  { id: 150, name: 'PP', parentId: 148 },
  { id: 151, name: 'Chrome', parentId: 152 },
  { id: 152, name: 'P Trap', parentId: 147 },
  { id: 153, name: 'PP', parentId: 152 },
  { id: 154, name: 'Space Saver Trap', parentId: 147 },
  { id: 155, name: 'PP', parentId: 154 },
  { id: 156, name: 'Accessories', parentId: 147 },
  { id: 157, name: 'PP', parentId: 156 },
  { id: 158, name: 'MagikOne Flexible', parentId: 147 },
  { id: 159, name: 'PP', parentId: 158 },
  { id: 160, name: 'Arc', parentId: 29 },
  { id: 161, name: 'Orbit', parentId: 68 },
  { id: 162, name: 'Orbit', parentId: 137 },
  { id: 163, name: "Queen's Prime", parentId: 29 },
  { id: 164, name: 'CHROME', parentId: 158 }
];

export const groups: any[] = [
  { id: 1, name: 'Current Assets', parentId: 0 },
  { id: 2, name: 'Current Liabilities', parentId: 0 },
  { id: 3, name: 'Loans (Liability)', parentId: 0 },
  { id: 4, name: 'Capital Account', parentId: 0 },
  { id: 5, name: 'Direct Expenses', parentId: 0 },
  { id: 6, name: 'Indirect Expenses', parentId: 0 },
  { id: 7, name: 'Investment', parentId: 0 },
  { id: 8, name: 'Branch / Divisions', parentId: 0 },
  { id: 9, name: 'Sales Accounts', parentId: 0 },
  { id: 10, name: 'Purchase Accounts', parentId: 0 },
  { id: 11, name: 'Direct Incomes', parentId: 0 },
  { id: 12, name: 'Indirect Income', parentId: 0 },
  { id: 13, name: 'Misc Expense (Asset)', parentId: 0 },
  { id: 14, name: 'Fixed Assets', parentId: 0 },
  { id: 15, name: 'Suspense A/c', parentId: 0 },
  { id: 16, name: 'Sundry Creditors', parentId: 2 },
  { id: 17, name: 'Sundry Debtors', parentId: 1 },
  { id: 18, name: 'Cash In Hand', parentId: 1 },
  { id: 19, name: 'Bank Account', parentId: 1 },
  { id: 20, name: 'Bank OD Account', parentId: 3 },
  { id: 21, name: 'Deposit (Asset)', parentId: 1 },
  { id: 22, name: 'Loan & Advance (Asset)', parentId: 1 },
  { id: 23, name: 'Secured Loans', parentId: 3 },
  { id: 24, name: 'Unsecured Loans', parentId: 3 },
  { id: 25, name: 'Duties & Taxes', parentId: 2 },
  { id: 26, name: 'Reserves & Surplus', parentId: 4 },
  { id: 27, name: 'Stock-In-Hand', parentId: 1 },
  { id: 28, name: 'Provisions', parentId: 2 },
  { id: 29, name: 'Sales @ Jaquar', parentId: 9 },
  { id: 30, name: 'Sales @ Essco', parentId: 9 },
  { id: 31, name: 'Sales @ Artize', parentId: 9 },
  { id: 32, name: 'Purchase @ Jaquar', parentId: 10 },
  { id: 33, name: 'Purchase @ Essco', parentId: 10 },
  { id: 34, name: 'Purchase @ Artize', parentId: 10 },
  { id: 35, name: 'Traders', parentId: 17 },
  { id: 36, name: 'Non-Traders', parentId: 17 },
  { id: 37, name: 'Temporary Ledger', parentId: 17 },
  { id: 38, name: 'Bank Inerest', parentId: 6 },
  { id: 39, name: 'Telephone Bill Expenses', parentId: 6 },
  { id: 40, name: 'Salary Expenses', parentId: 6 },
  { id: 41, name: 'Staff Advances', parentId: 22 },
  { id: 42, name: 'Staff Loan', parentId: 22 },
  { id: 43, name: 'Block Assets I', parentId: 14 },
  { id: 44, name: 'Block Assets II', parentId: 14 },
  { id: 45, name: 'Block Assets III', parentId: 14 },
  { id: 46, name: 'Block Assets IV', parentId: 14 },
  { id: 47, name: 'Jaquar RD', parentId: 35 }
];
